package com.jifenke.lepluslive.mq.dto;


public enum WxMsgType {
  LIVE_DELIVER_GOODS,
  LIVE_CHARGE_SUCCESSED,
  LIVE_GIFT_BAG,
  LIVE_PREPAID_REFILL,
  PAY_CHARGE_SUCCESSED,
  PAY_TRANSFER_SUCCESSED,
  SHOP_QRCODE_EXPIRATION,
  SHOP_DELIVER_GOODS,
  SHOP_WITHDRAWALS_APPLY,

}
